# Generated by Django 3.0.7 on 2020-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_path_file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
