# Generated by Django 3.0.7 on 2020-07-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(default='tba', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(default='tba', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_path_file', models.ImageField(upload_to='images/')),
                ('label', models.CharField(default='add label', max_length=200)),
                ('upload_date', models.DateTimeField(null=True, verbose_name='date uploaded')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='batapp.StatusPicture')),
            ],
        ),
    ]
