# Generated by Django 3.0.7 on 2020-07-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='tagged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picture',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('belongs_to_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectangles', to='batapp.Picture')),
            ],
        ),
    ]
