# Generated by Django 3.0.7 on 2020-06-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(default='tba', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(default='tba', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='label',
            field=models.CharField(default='add label', max_length=200),
        ),
        migrations.AddField(
            model_name='picture',
            name='upload_date',
            field=models.DateTimeField(null=True, verbose_name='date uploaded'),
        ),
        migrations.AddField(
            model_name='picture',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='batapp.StatusPicture'),
        ),
    ]
