# Generated by Django 3.0.7 on 2020-07-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batapp', '0002_auto_20200703_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nothing', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='rect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forpic', to='batapp.CoordHead'),
        ),
        migrations.AlterField(
            model_name='coord',
            name='belongs_to_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectangles', to='batapp.CoordHead'),
        ),
    ]
