# Generated by Django 3.0.6 on 2020-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batapp', '0003_auto_20200703_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testfilecreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_file', models.FileField(null=True, upload_to='testfiles/')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='metadata_file',
            field=models.FileField(null=True, upload_to='metafiles/'),
        ),
    ]
