# Generated by Django 3.0.8 on 2020-07-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batapp', '0004_auto_20200723_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
